{
 "title": "Postgres",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Database size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname!=\"template0\", datname!=\"template1\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Number of locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_locks_count{datname!=\"template0\", datname!=\"template1\"}",
     "legendFormat": "{{datname}} {{mode}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_up{}", "legendFormat": "__auto" }
   ]
  }
 ]
}